/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpb.gestaobibliotecadigital.views.avaliacoes;

import br.edu.ifpb.gestaobibliotecadigital.models.avaliacao.Avaliacao;
import br.edu.ifpb.gestaobibliotecadigital.models.livros.Livro;
import br.edu.ifpb.gestaobibliotecadigital.models.usuarios.Usuario;
import br.edu.ifpb.gestaobibliotecadigital.observers.AtualizarMediaObserver;
import br.edu.ifpb.gestaobibliotecadigital.services.impl.AvaliacaoService;
import javax.swing.JOptionPane;

public class Criar_AvaliacoesLivro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Criar_AvaliacoesLivro.class.getName());
    private Livro livro;
    private Usuario usuario;

    /**
     * Creates new form Criar_AvaliacoesLivro
     */
    public Criar_AvaliacoesLivro() {
        initComponents();
    }

    public Criar_AvaliacoesLivro(Usuario usuario, Livro livro) {
        initComponents();
        this.livro = livro;
        this.usuario = usuario;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comentario = new javax.swing.JLabel();
        nota = new javax.swing.JLabel();
        inputComentario = new javax.swing.JScrollPane();
        coment = new javax.swing.JTextArea();
        inputNota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        enviarComentario = new javax.swing.JButton();
        viewAvaliacao = new javax.swing.JToggleButton();
        usuarioPanel1 = new br.edu.ifpb.gestaobibliotecadigital.views.components.UsuarioPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        comentario.setText("Comentario");

        nota.setText("Nota");

        coment.setColumns(20);
        coment.setRows(5);
        inputComentario.setViewportView(coment);

        inputNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNotaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("AVALIAÇÃO");

        enviarComentario.setText("Enviar");
        enviarComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarComentarioActionPerformed(evt);
            }
        });

        viewAvaliacao.setText("Ver Avaliações");
        viewAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAvaliacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usuarioPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewAvaliacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enviarComentario))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comentario)
                            .addComponent(nota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputNota, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(usuarioPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comentario)
                    .addComponent(inputComentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(nota))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarComentario)
                    .addComponent(viewAvaliacao))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNotaActionPerformed

    private void enviarComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarComentarioActionPerformed
        // TODO add your handling code here:
        AvaliacaoService avaliacaoService = new AvaliacaoService();
        
        String comentario = coment.getText().trim();
        String nota = inputNota.getText().trim();
        
        if (comentario.isEmpty() || nota.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (Integer.parseInt(nota) < 1 || Integer.parseInt(nota) > 5) {
            JOptionPane.showMessageDialog(null, "A nota deve estar entre 1 e 5!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Avaliacao avaliacao = new Avaliacao(livro, usuario, Integer.parseInt(nota), comentario, livro.getId());
        avaliacaoService.adicionarAvaliacao(avaliacao);
        
        AtualizarMediaObserver atualizarMediaObserver = new AtualizarMediaObserver(avaliacaoService);
        avaliacaoService.adicionarObserver(atualizarMediaObserver);
        atualizarMediaObserver.notificarNovaAvaliacao(avaliacao);
        
        JOptionPane.showMessageDialog(null, "Comentário enviado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        coment.setText("");
        inputNota.setText("");


        //AvaliacaoRepository repo_avaliacoes = AvaliacaoRepository.getInstance();;
        //System.out.println(repo_avaliacoes.listar());
    }//GEN-LAST:event_enviarComentarioActionPerformed

    private void viewAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAvaliacaoActionPerformed
        // TODO add your handling code here:
        new LivroRecomendacao(usuario).setVisible(true);
    }//GEN-LAST:event_viewAvaliacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Criar_AvaliacoesLivro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea coment;
    private javax.swing.JLabel comentario;
    private javax.swing.JButton enviarComentario;
    private javax.swing.JScrollPane inputComentario;
    private javax.swing.JTextField inputNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nota;
    private br.edu.ifpb.gestaobibliotecadigital.views.components.UsuarioPanel usuarioPanel1;
    private javax.swing.JToggleButton viewAvaliacao;
    // End of variables declaration//GEN-END:variables
}
