/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpb.gestaobibliotecadigital.views.avaliacoes;

import br.edu.ifpb.gestaobibliotecadigital.models.livros.Livro;
import br.edu.ifpb.gestaobibliotecadigital.models.usuarios.Usuario;
import br.edu.ifpb.gestaobibliotecadigital.recommendations.CriterioAutor;
import br.edu.ifpb.gestaobibliotecadigital.recommendations.CriterioMaisAvaliados;
import br.edu.ifpb.gestaobibliotecadigital.recommendations.CriterioMaisLidos;
import br.edu.ifpb.gestaobibliotecadigital.recommendations.CriterioRecomendacao;
import br.edu.ifpb.gestaobibliotecadigital.repositories.EmprestimoRepository;
import br.edu.ifpb.gestaobibliotecadigital.repositories.LivroRepository;
import br.edu.ifpb.gestaobibliotecadigital.services.impl.AvaliacaoService;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class LivroRecomendacao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LivroRecomendacao.class.getName());

    /**
     * Creates new form LivroRecomendacao
     */
    public LivroRecomendacao() {
        initComponents();
    }

    public LivroRecomendacao(Usuario usuario) {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        ver = new javax.swing.JButton();
        ranking = new javax.swing.JButton();
        destaques = new javax.swing.JButton();
        autor = new javax.swing.JButton();
        usuarioPanel1 = new br.edu.ifpb.gestaobibliotecadigital.views.components.UsuarioPanel();
        MaisFiltros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Autor"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        ver.setText("Ver Livro");
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });

        ranking.setText("Ranking");
        ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankingActionPerformed(evt);
            }
        });

        destaques.setText("Destaques Semanais");
        destaques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destaquesActionPerformed(evt);
            }
        });

        autor.setText("Autor");
        autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorActionPerformed(evt);
            }
        });

        MaisFiltros.setText("Mais Filtros Recomendação");
        MaisFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaisFiltrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(destaques)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ranking)
                .addGap(18, 18, 18)
                .addComponent(autor)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(MaisFiltros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ver)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(usuarioPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usuarioPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ranking)
                    .addComponent(destaques)
                    .addComponent(autor))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ver)
                    .addComponent(MaisFiltros))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        // TODO add your handling code here:
        /*DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        Object[] dados = {"Maria", "Livro"};
        modelo.setNumRows(0);
        modelo.addRow(dados);*/
        
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        int linha = tabela.getSelectedRow();
        var texto = modelo.getValueAt(linha, 0);
        
        for (Livro livro : LivroRepository.getInstance().listar()){
            if (livro.getTitulo().equals(texto)){
                new Mostrar_AvaliacoesLivro(livro).setVisible(true);
            }
        }
        
    }//GEN-LAST:event_verActionPerformed

    private void rankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankingActionPerformed
        // TODO add your handling code here:
        
        EmprestimoRepository repoEmprestimos = EmprestimoRepository.getInstance();
        AvaliacaoService avaliacaoService = new AvaliacaoService();
        List<Livro> livros = LivroRepository.getInstance().listar();

        
        CriterioRecomendacao criterioMaisLidos = new CriterioMaisLidos(repoEmprestimos);
        CriterioRecomendacao criterioMaisAvaliados = new CriterioMaisAvaliados(avaliacaoService);
        CriterioRecomendacao criterioAutor = new CriterioAutor(livros);

        criterioMaisAvaliados.setProximo(criterioMaisLidos);
        criterioAutor.setProximo(criterioMaisLidos);
        criterioMaisLidos.setProximo(null);


        //Livro livro = LivroRepository.getInstance().listar().get(0);
//        String recomendacao = criterioMaisLidos.recomendar(livro);

        //JOptionPane.showMessageDialog(this, recomendacao);
        
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        
        modelo.setNumRows(0);     
        
        for (Livro livro : livros) {
            String recomendacao = criterioMaisLidos.recomendar(livro);
            if (recomendacao != null) {
                Object[] linha = {livro.getTitulo(), livro.getAutor()}; // ou conforme seu modelo de dados
                modelo.addRow(linha);
                //dadosList.add(recomendacao);
                // new Mostrar_AvaliacoesLivro(livro).setVisible(true);
            }
        }
    }//GEN-LAST:event_rankingActionPerformed

    private void destaquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destaquesActionPerformed
        // TODO add your handling code here:
        EmprestimoRepository repoEmprestimos = EmprestimoRepository.getInstance();
        AvaliacaoService avaliacaoService = new AvaliacaoService();
        List<Livro> livros = LivroRepository.getInstance().listar();

        CriterioRecomendacao criterioMaisLidos = new CriterioMaisLidos(repoEmprestimos);
        CriterioRecomendacao criterioMaisAvaliados = new CriterioMaisAvaliados(avaliacaoService);
        CriterioRecomendacao criterioAutor = new CriterioAutor(livros);

        criterioMaisLidos.setProximo(criterioMaisAvaliados);
        criterioMaisAvaliados.setProximo(null);

        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        
        for(Livro livro : livros){
            String recomendacao_nota = criterioMaisAvaliados.recomendar(livro);
            if (recomendacao_nota != null) {
                Object[] linha = {livro.getTitulo(), livro.getAutor()}; // ou conforme seu modelo de dados
                modelo.addRow(linha);
            }
        }
    }//GEN-LAST:event_destaquesActionPerformed

    private void autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorActionPerformed
        // TODO add your handling code here:
        
        EmprestimoRepository repoEmprestimos = EmprestimoRepository.getInstance();
        AvaliacaoService avaliacaoService = new AvaliacaoService();
        List<Livro> livros = LivroRepository.getInstance().listar();
        
        CriterioRecomendacao criterioMaisLidos = new CriterioMaisLidos(repoEmprestimos);
        CriterioRecomendacao criterioMaisAvaliados = new CriterioMaisAvaliados(avaliacaoService);
        CriterioRecomendacao criterioAutor = new CriterioAutor(livros);

        criterioMaisAvaliados.setProximo(criterioAutor);
        criterioMaisLidos.setProximo(criterioMaisAvaliados);
        criterioAutor.setProximo(null);
        
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();        
        modelo.setNumRows(0);
        
        for (Livro livro : livros) {
            String recomendacao = criterioMaisAvaliados.recomendar(livro);
            if (livro.getTitulo().equals(recomendacao)){
                Object[] linha = {livro.getTitulo(), livro.getAutor()};
                modelo.addRow(linha);
            }
        }
    }//GEN-LAST:event_autorActionPerformed

    private void MaisFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaisFiltrosActionPerformed
        // TODO add your handling code here:
        new MaisRecomendacoes().setVisible(true);
    }//GEN-LAST:event_MaisFiltrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LivroRecomendacao().setVisible(true));
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MaisFiltros;
    private javax.swing.JButton autor;
    private javax.swing.JButton destaques;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ranking;
    private javax.swing.JTable tabela;
    private br.edu.ifpb.gestaobibliotecadigital.views.components.UsuarioPanel usuarioPanel1;
    private javax.swing.JButton ver;
    // End of variables declaration//GEN-END:variables
}
