/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpb.gestaobibliotecadigital.views.avaliacoes;

import br.edu.ifpb.gestaobibliotecadigital.recommendations.CriterioMediaCategoria;
import br.edu.ifpb.gestaobibliotecadigital.models.livros.Livro;
import br.edu.ifpb.gestaobibliotecadigital.recommendations.CriterioMediaAutor;
import br.edu.ifpb.gestaobibliotecadigital.repositories.LivroRepository;
import br.edu.ifpb.gestaobibliotecadigital.services.impl.AvaliacaoService;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;


public class MaisRecomendacoes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MaisRecomendacoes.class.getName());
    
    private final LivroRepository livroRepository = LivroRepository.getInstance();
    private final AvaliacaoService avaliacaoService = new AvaliacaoService();

    /**
     * Creates new form MaisRecomendacoes
     */
    public MaisRecomendacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        categoria = new javax.swing.JButton();
        autor = new javax.swing.JButton();
        media = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Autor", "Media", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel1.setText("Lista Recomendacoes Pela Média");

        categoria.setText("Filtro Categoria");
        categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaActionPerformed(evt);
            }
        });

        autor.setText("Filtro Autor");
        autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorActionPerformed(evt);
            }
        });

        media.setText("Média");
        media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(media)
                        .addGap(18, 18, 18)
                        .addComponent(autor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoria))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autor)
                    .addComponent(categoria)
                    .addComponent(media))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaActionPerformed
        // TODO add your handling code here:
        List<Livro> livros = livroRepository.listar();

        CriterioMediaCategoria criterio = new CriterioMediaCategoria(avaliacaoService);
        Map<String, List<Livro>> livrosPorCategoria = criterio.ordenarPorMediaECategoria(livros);

        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        model.setRowCount(0); 

        for (Map.Entry<String, List<Livro>> entry : livrosPorCategoria.entrySet()) {
            String categoria = entry.getKey();
            List<Livro> livrosOrdenados = entry.getValue();

            for (Livro livro : livrosOrdenados) {
                double media = avaliacaoService.calcularMediaAvaliacoes(livro.getId());
                model.addRow(new Object[]{livro.getTitulo(), livro.getAutor(), String.format("%.2f", media), categoria});
            }
        }
    }//GEN-LAST:event_categoriaActionPerformed

    private void autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorActionPerformed
        // TODO add your handling code here:
        List<Livro> livros = livroRepository.listar();

        CriterioMediaAutor criterio = new CriterioMediaAutor(avaliacaoService);
        Map<String, List<Livro>> livrosPorAutor = criterio.ordenarPorMediaEAutor(livros);

        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        model.setRowCount(0); 

        for (Map.Entry<String, List<Livro>> entry : livrosPorAutor.entrySet()) {
            String autor = entry.getKey();
            List<Livro> livrosOrdenados = entry.getValue();

            for (Livro livro : livrosOrdenados) {
                double media = avaliacaoService.calcularMediaAvaliacoes(livro.getId());
                model.addRow(new Object[]{livro.getTitulo(), autor, String.format("%.2f", media), livro.getCategoria()});
            }
        }
    }//GEN-LAST:event_autorActionPerformed

    private void mediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediaActionPerformed
        // TODO add your handling code here:
        List<Livro> livros = livroRepository.listar();

        List<Livro> livrosOrdenados = livros.stream()
                .sorted((livro1, livro2) -> {
                    double media1 = avaliacaoService.calcularMediaAvaliacoes(livro1.getId());
                    double media2 = avaliacaoService.calcularMediaAvaliacoes(livro2.getId());
                    return Double.compare(media2, media1); 
                })
                .collect(Collectors.toList());

        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        model.setRowCount(0); 

        for (Livro livro : livrosOrdenados) {
            double media = avaliacaoService.calcularMediaAvaliacoes(livro.getId());
            model.addRow(new Object[]{livro.getTitulo(), livro.getAutor(), String.format("%.2f", media), livro.getCategoria()});
        }
    }//GEN-LAST:event_mediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MaisRecomendacoes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autor;
    private javax.swing.JButton categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton media;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
