/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpb.gestaobibliotecadigital.views.avaliacoes;

import br.edu.ifpb.gestaobibliotecadigital.models.avaliacao.Avaliacao;
import br.edu.ifpb.gestaobibliotecadigital.models.livros.Livro;
import br.edu.ifpb.gestaobibliotecadigital.models.usuarios.Usuario;
import br.edu.ifpb.gestaobibliotecadigital.repositories.AvaliacaoRepository;
import javax.swing.table.DefaultTableModel;


public class Mostrar_AvaliacoesLivro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mostrar_AvaliacoesLivro.class.getName());
    private Livro livroAtual;

    /**
     * Creates new form AvaliacoesLivro
     */
    public Mostrar_AvaliacoesLivro(){
        initComponents();
    }
    public Mostrar_AvaliacoesLivro(Usuario usuario){
        initComponents();
    }
    public Mostrar_AvaliacoesLivro(Livro livro) {
        initComponents();
        
        livroAtual = livro;
        AvaliacaoRepository repositorio = AvaliacaoRepository.getInstance();
        
        
        for (Avaliacao avaliacao : repositorio.listar()){
                if (avaliacao.getId().equals(livro.getId())){
                    mediaNota.setText(String.valueOf(avaliacao.getNota()));// Média Nota                    
            }
        }

        NomeLivro.setText(livro.getTitulo()); // Nome do livro
        nomeAutor.setText(livro.getAutor());  // Nome do autor

        // Aqui você pode buscar a média de avaliações e comentários se quiser
        // Ex: jLabel2.setText("Média: " + calcularMedia(livro));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        verComent = new javax.swing.JButton();
        NomeLivro = new javax.swing.JLabel();
        mediaNota = new javax.swing.JLabel();
        nomeAutor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        usuarioPanel1 = new br.edu.ifpb.gestaobibliotecadigital.views.components.UsuarioPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        verComent.setText("Ver Comentários");
        verComent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verComentActionPerformed(evt);
            }
        });

        NomeLivro.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        NomeLivro.setText("Nome Livro");

        mediaNota.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        mediaNota.setText("Sem Nota");

        nomeAutor.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        nomeAutor.setText("Nome Autor");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Comentário", "Autor"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeAutor)
                                .addGap(18, 18, 18)
                                .addComponent(mediaNota))
                            .addComponent(NomeLivro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usuarioPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verComent)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NomeLivro)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mediaNota)
                            .addComponent(nomeAutor)))
                    .addComponent(usuarioPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(verComent)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verComentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verComentActionPerformed
        // TODO add your handling code here:
        AvaliacaoRepository repositorio = AvaliacaoRepository.getInstance();

        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);

        for (Avaliacao avaliacao : repositorio.listar()) {
            if (avaliacao.getId().equals(livroAtual.getId())) {
                Object[] linha = {avaliacao.getComentario(), avaliacao.getUsuario().getNome()};
                modelo.addRow(linha);
            }
        }
    }//GEN-LAST:event_verComentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mostrar_AvaliacoesLivro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomeLivro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mediaNota;
    private javax.swing.JLabel nomeAutor;
    private javax.swing.JTable tabela;
    private br.edu.ifpb.gestaobibliotecadigital.views.components.UsuarioPanel usuarioPanel1;
    private javax.swing.JButton verComent;
    // End of variables declaration//GEN-END:variables
}
