package br.edu.ifpb.gestaobibliotecadigital.views.emprestimos;

import br.edu.ifpb.gestaobibliotecadigital.controllers.EmprestimoController;
import br.edu.ifpb.gestaobibliotecadigital.filters.EmprestimoFiltro;
import br.edu.ifpb.gestaobibliotecadigital.models.emprestimos.Emprestimo;
import java.util.List;
import javax.swing.JOptionPane;

public class ListaEmprestimos extends javax.swing.JFrame {

    private final EmprestimoController emprestimoController = new EmprestimoController();
    private List<Emprestimo> listaEmprestimos;
    private String pesquisa = "";
    private EmprestimoFiltro filtro = new EmprestimoFiltro();

    public ListaEmprestimos() {
        initComponents();
        atualizarListaEmprestimos();

        // Define os dados na tabela
        tabelaEmprestimos.setDados(listaEmprestimos);

        // Atualiza a lista de empréstimos quando houver alguma alteração
        acoesEmprestimo.events.onUpdate(() -> {
            atualizarListaEmprestimos();
            filtrar();
        });

        // Filtra a lista de empréstimos quando digitar na caixa de pesquisa
        pesquisar.events.onUpdate(() -> {
            pesquisa = pesquisar.getText();
            filtrar();
        });

        // Filtra a lista de empréstimos quando pressionar "Pesquisar"
        pesquisaAvancadaEmprestimos.events.onUpdate(() -> {
            filtro = pesquisaAvancadaEmprestimos.getFiltro();
            filtrar();
        });
    }

    /**
     * Atualiza a lista de empréstimos
     */
    private void atualizarListaEmprestimos() {
        try {
            listaEmprestimos = emprestimoController.listarEmprestimos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao listar empréstimos", JOptionPane.ERROR_MESSAGE);
            throw ex;
        }
    }

    /**
     * Filtra a lista de empréstimos
     */
    private void filtrar() {
        EmprestimoFiltro filtroClone = (EmprestimoFiltro) filtro.clone();

        // Define a lista completa de empréstimos no filtro
        filtroClone.setItens(listaEmprestimos);

        // Se a caixa de pesquisa não estiver vazia, filtra
        if (!pesquisa.trim().equals("")) {
            filtroClone.pesquisar(pesquisa);
        }

        // Atualiza a lista de empréstimos
        tabelaEmprestimos.setDados(filtroClone.filtrar());
        onItemDestacadoEmprestimos(null);
    }

    /**
     * Ao destacar um item da tabela
     */
    private void onItemDestacadoEmprestimos(Emprestimo item) {
        acoesEmprestimo.setEmprestimo(item);
        detalhesEmprestimo.setEmprestimo(item);
        detalhesLivro.setLivro(item == null ? null : item.getLivro());
        detalhesUsuario.setUsuario(item == null ? null : item.getUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        usuarioPanel = new br.edu.ifpb.gestaobibliotecadigital.views.components.UsuarioPanel();
        pesquisar = new br.edu.ifpb.gestaobibliotecadigital.views.components.PesquisarPanel();
        pesquisaAvancadaEmprestimos = new br.edu.ifpb.gestaobibliotecadigital.views.emprestimos.PesquisaAvancadaEmprestimos();
        tabelaEmprestimos = new br.edu.ifpb.gestaobibliotecadigital.views.emprestimos.TabelaEmprestimos(){
            @Override
            protected void onItemDestacado(Emprestimo item) {
                onItemDestacadoEmprestimos(item);
            }
        };
        acoesEmprestimo = new br.edu.ifpb.gestaobibliotecadigital.views.emprestimos.AcoesEmprestimo();
        detalhesEmprestimo = new br.edu.ifpb.gestaobibliotecadigital.views.emprestimos.DetalhesEmprestimo();
        detalhesLivro = new br.edu.ifpb.gestaobibliotecadigital.views.livros.DetalhesLivro();
        detalhesUsuario = new br.edu.ifpb.gestaobibliotecadigital.views.usuarios.DetalhesUsuario();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empréstimos");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 560));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo.setText("Listagem de Empréstimos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo)
                            .addComponent(pesquisaAvancadaEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acoesEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(detalhesEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(detalhesLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(detalhesUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tabelaEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(usuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addComponent(usuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabelaEmprestimos, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acoesEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(detalhesLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(detalhesUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detalhesEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pesquisaAvancadaEmprestimos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaEmprestimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.edu.ifpb.gestaobibliotecadigital.views.emprestimos.AcoesEmprestimo acoesEmprestimo;
    private br.edu.ifpb.gestaobibliotecadigital.views.emprestimos.DetalhesEmprestimo detalhesEmprestimo;
    private br.edu.ifpb.gestaobibliotecadigital.views.livros.DetalhesLivro detalhesLivro;
    private br.edu.ifpb.gestaobibliotecadigital.views.usuarios.DetalhesUsuario detalhesUsuario;
    private br.edu.ifpb.gestaobibliotecadigital.views.emprestimos.PesquisaAvancadaEmprestimos pesquisaAvancadaEmprestimos;
    private br.edu.ifpb.gestaobibliotecadigital.views.components.PesquisarPanel pesquisar;
    private br.edu.ifpb.gestaobibliotecadigital.views.emprestimos.TabelaEmprestimos tabelaEmprestimos;
    private javax.swing.JLabel titulo;
    private br.edu.ifpb.gestaobibliotecadigital.views.components.UsuarioPanel usuarioPanel;
    // End of variables declaration//GEN-END:variables
}
