package br.edu.ifpb.gestaobibliotecadigital.views.reservas;

import br.edu.ifpb.gestaobibliotecadigital.controllers.EmprestimoController;
import br.edu.ifpb.gestaobibliotecadigital.models.emprestimos.Reserva;
import br.edu.ifpb.gestaobibliotecadigital.models.usuarios.Administrador;
import br.edu.ifpb.gestaobibliotecadigital.models.usuarios.Usuario;
import br.edu.ifpb.gestaobibliotecadigital.session.UserSessionManager;
import br.edu.ifpb.gestaobibliotecadigital.views.components.UpdateObserver;
import java.awt.Dialog;
import javax.swing.JOptionPane;

public class AcoesReserva extends javax.swing.JPanel {

    private Usuario usuarioLogado = UserSessionManager.getInstance().getUsuarioLogado();
    private Reserva reserva;
    public final UpdateObserver events = new UpdateObserver();
    private final EmprestimoController emprestimoController = new EmprestimoController();

    public AcoesReserva() {
        initComponents();
        initBotoes();
    }

    /**
     * Atualiza a reserva selecionada
     */
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;

        remover.setEnabled(reserva != null);
        cancelar.setEnabled(reserva != null && !reserva.encerrada());
    }

    /**
     * Oculta botões de ações como adicionar/remover/devolver/multa paga para
     * usuários comuns
     */
    private void initBotoes() {
        Usuario usuarioLogado = UserSessionManager.getInstance().getUsuarioLogado();
        boolean isAdmin = usuarioLogado != null && usuarioLogado instanceof Administrador;
        remover.setVisible(isAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atualizar = new javax.swing.JButton();
        adicionar = new javax.swing.JButton();
        remover = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        atualizar.setText("Atualizar");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        adicionar.setText("Adicionar");
        adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarActionPerformed(evt);
            }
        });

        remover.setText("Remover");
        remover.setEnabled(false);
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(atualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(remover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(cancelar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(adicionar)
                .addComponent(remover)
                .addComponent(cancelar)
                .addComponent(atualizar))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        events.emit();
    }//GEN-LAST:event_atualizarActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed

        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que vai remover esta reserva?",
                "Remover reserva",
                JOptionPane.YES_NO_OPTION
        );

        if (resposta == JOptionPane.YES_OPTION) {
            try {
                emprestimoController.excluirReserva(reserva);
                events.emit();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(
                        this,
                        ex.getMessage(),
                        "Erro ao excluir reserva",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_removerActionPerformed

    private void adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarActionPerformed
        Dialog criarReservaDialog; 
        if (usuarioLogado instanceof Administrador) {
            criarReservaDialog = new CriarReserva(null, true);
        } else {
            criarReservaDialog = new ReservarLivro(null, true);
        }
        criarReservaDialog.setVisible(true);
        events.emit();
    }//GEN-LAST:event_adicionarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que vai cancelar a reserva?",
                "Cancelar reserva",
                JOptionPane.YES_NO_OPTION
        );

        if (resposta == JOptionPane.YES_OPTION) {
            try {
                emprestimoController.cancelarReserva(reserva);
                events.emit();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(
                        this,
                        ex.getMessage(),
                        "Erro ao cancelar reserva",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar;
    private javax.swing.JButton atualizar;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton remover;
// End of variables declaration//GEN-END:variables
}
