package br.edu.ifpb.gestaobibliotecadigital.views.reservas;

import br.edu.ifpb.gestaobibliotecadigital.controllers.EmprestimoController;
import br.edu.ifpb.gestaobibliotecadigital.filters.ReservaFiltro;
import br.edu.ifpb.gestaobibliotecadigital.models.emprestimos.Reserva;
import java.util.List;
import javax.swing.JOptionPane;

public class ListaReservas extends javax.swing.JFrame {
    private final EmprestimoController emprestimoController = new EmprestimoController();
    private List<Reserva> listaReservas;
    private String pesquisa = "";
    private ReservaFiltro filtro = new ReservaFiltro();

    public ListaReservas() {
        initComponents();
        atualizarListaReservas();

        // Define os dados na tabela
        tabelaReservas.setDados(listaReservas);

        // Atualiza a lista de reservas quando houver alguma alteração
        acoesReserva.events.onUpdate(() -> {
            atualizarListaReservas();
            filtrar();
        });

        // Filtra a lista de reservas quando digitar na caixa de pesquisa
        pesquisar.events.onUpdate(() -> {
            pesquisa = pesquisar.getText();
            filtrar();
        });

        // Filtra a lista de reservas quando pressionar "Pesquisar"
        pesquisaAvancadaReservas.events.onUpdate(() -> {
            filtro = pesquisaAvancadaReservas.getFiltro();
            filtrar();
        });
    }
    
     /**
     * Atualiza a lista de reservas
     */
    private void atualizarListaReservas() {
        try {
            listaReservas = emprestimoController.listarReservas();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao listar reservas", JOptionPane.ERROR_MESSAGE);
            throw ex;
        }
    }

    /**
     * Filtra a lista de reservas
     */
    private void filtrar() {
        ReservaFiltro filtroClone = (ReservaFiltro) filtro.clone();
        
        // Define a lista completa de reservas no filtro
        filtroClone.setItens(listaReservas);
        
        // Se a caixa de pesquisa não estiver vazia, filtra
        if (!pesquisa.trim().equals("")) {
            filtroClone.pesquisar(pesquisa);
        }
        
        // Atualiza a lista de reservas
        tabelaReservas.setDados(filtroClone.filtrar());
        onItemDestacadoReservas(null);
    }

    /**
     * Ao destacar um item da tabela
     */
    private void onItemDestacadoReservas(Reserva item) {
        acoesReserva.setReserva(item);
        detalhesReserva.setReserva(item);
        detalhesLivro.setLivro(item == null ? null : item.getLivro());
        detalhesUsuario.setUsuario(item == null ? null : item.getUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        usuarioPanel = new br.edu.ifpb.gestaobibliotecadigital.views.components.UsuarioPanel();
        pesquisar = new br.edu.ifpb.gestaobibliotecadigital.views.components.PesquisarPanel();
        pesquisaAvancadaReservas = new br.edu.ifpb.gestaobibliotecadigital.views.reservas.PesquisaAvancadaReservas();
        tabelaReservas = new br.edu.ifpb.gestaobibliotecadigital.views.reservas.TabelaReservas(){
            @Override
            protected void onItemDestacado(Reserva item) {
                onItemDestacadoReservas(item);
            }
        };
        acoesReserva = new br.edu.ifpb.gestaobibliotecadigital.views.reservas.AcoesReserva();
        detalhesReserva = new br.edu.ifpb.gestaobibliotecadigital.views.reservas.DetalhesReserva();
        detalhesLivro = new br.edu.ifpb.gestaobibliotecadigital.views.livros.DetalhesLivro();
        detalhesUsuario = new br.edu.ifpb.gestaobibliotecadigital.views.usuarios.DetalhesUsuario();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservas");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 560));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo.setText("Listagem de Reservas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo)
                            .addComponent(pesquisaAvancadaReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acoesReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(detalhesReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(detalhesLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(detalhesUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tabelaReservas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(usuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addComponent(usuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabelaReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acoesReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(detalhesLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(detalhesUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detalhesReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pesquisaAvancadaReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.edu.ifpb.gestaobibliotecadigital.views.reservas.AcoesReserva acoesReserva;
    private br.edu.ifpb.gestaobibliotecadigital.views.livros.DetalhesLivro detalhesLivro;
    private br.edu.ifpb.gestaobibliotecadigital.views.reservas.DetalhesReserva detalhesReserva;
    private br.edu.ifpb.gestaobibliotecadigital.views.usuarios.DetalhesUsuario detalhesUsuario;
    private br.edu.ifpb.gestaobibliotecadigital.views.reservas.PesquisaAvancadaReservas pesquisaAvancadaReservas;
    private br.edu.ifpb.gestaobibliotecadigital.views.components.PesquisarPanel pesquisar;
    private br.edu.ifpb.gestaobibliotecadigital.views.reservas.TabelaReservas tabelaReservas;
    private javax.swing.JLabel titulo;
    private br.edu.ifpb.gestaobibliotecadigital.views.components.UsuarioPanel usuarioPanel;
    // End of variables declaration//GEN-END:variables
}
