package br.edu.ifpb.gestaobibliotecadigital.views.livros;

import br.edu.ifpb.gestaobibliotecadigital.models.livros.decorators.LivroComCapaAlternativa;
import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import br.edu.ifpb.gestaobibliotecadigital.models.livros.Livro;

public class CapaLivro extends javax.swing.JPanel {

    private Livro livro;

    public CapaLivro() {
        initComponents();
        setLivro(null);
    }

    /**
     * Atualiza o livro selecionado
     *
     * @param livro
     */
    public void setLivro(Livro livro) {
        this.livro = livro;

        // Limpa sempre ao começar
        capaDoLivro.setIcon(null);
        capaDoLivro.setText("Indisponível");
        if (livro == null) {
            capaDoLivro.setText("Indisponível");
        } else {
            if (livro instanceof LivroComCapaAlternativa livroComCapa) {
                try {
                    ImageIcon iconOriginal = new ImageIcon(new URL(livroComCapa.getUrlCapa()));
                    Image imgReduzida = iconOriginal.getImage().getScaledInstance(186, 200, Image.SCALE_SMOOTH);
                    capaDoLivro.setIcon(new ImageIcon(imgReduzida));
                    capaDoLivro.setText(null);
                } catch (MalformedURLException e) {
                    capaDoLivro.setIcon(null);
                    capaDoLivro.setText("Indisponível");
                }
                capaDoLivro.setText(livroComCapa.getUrlCapa());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capaDoLivro = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capaDoLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capaDoLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );

        capaDoLivro.setHorizontalAlignment(SwingConstants.CENTER);
        capaDoLivro.setVerticalAlignment(SwingConstants.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel capaDoLivro;
    // End of variables declaration//GEN-END:variables
}
