package br.edu.ifpb.gestaobibliotecadigital.views.livros;

import br.edu.ifpb.gestaobibliotecadigital.utils.Formatter;
import java.awt.Dimension;
import br.edu.ifpb.gestaobibliotecadigital.models.livros.Livro;

public class DetalhesLivro extends javax.swing.JPanel {

    private Livro livro;

    public DetalhesLivro() {
        initComponents();
        setLivro(null);
    }

    /**
     * Atualiza o livro selecionado
     *
     * @param livro
     */
    public void setLivro(Livro livro) {
        this.livro = livro;

        if (livro == null) {
            nomeLivro.setText(" ");
        } else {
            String texto = livro.getTitulo();
            if (texto.length() > 45) {
                texto = livro.getTitulo().substring(0, 40) + "...";
            }
            nomeLivro.setText(texto);
            anoPublicacao.setText(Formatter.of(livro.getAno()).toString());
            nomeEditora.setText(livro.getEditora());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        livroBorder = new javax.swing.JPanel();
        nomeLivro = new javax.swing.JLabel();
        anoPublicacao = new javax.swing.JLabel();
        nomeEditora = new javax.swing.JLabel();

        livroBorder.setBorder(javax.swing.BorderFactory.createTitledBorder("Livro"));
        livroBorder.setMinimumSize(new java.awt.Dimension(315, 169));

        nomeLivro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeLivro.setMaximumSize(new Dimension(315, 30));
        nomeLivro.setText("Nome do Livro");

        anoPublicacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        anoPublicacao.setText("Ano de Publicação");

        nomeEditora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomeEditora.setText("Nome da editora");

        javax.swing.GroupLayout livroBorderLayout = new javax.swing.GroupLayout(livroBorder);
        livroBorder.setLayout(livroBorderLayout);
        livroBorderLayout.setHorizontalGroup(
            livroBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livroBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(livroBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(anoPublicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(nomeEditora, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                .addContainerGap())
        );
        livroBorderLayout.setVerticalGroup(
            livroBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(livroBorderLayout.createSequentialGroup()
                .addComponent(nomeLivro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anoPublicacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeEditora)
                .addGap(0, 59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(livroBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(livroBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anoPublicacao;
    private javax.swing.JPanel livroBorder;
    private javax.swing.JLabel nomeEditora;
    private javax.swing.JLabel nomeLivro;
    // End of variables declaration//GEN-END:variables

}
