package br.edu.ifpb.gestaobibliotecadigital.views.livros;

import br.edu.ifpb.gestaobibliotecadigital.filters.LivroFiltro;
import br.edu.ifpb.gestaobibliotecadigital.services.impl.LivroService;
import br.edu.ifpb.gestaobibliotecadigital.utils.Helpers;
import br.edu.ifpb.gestaobibliotecadigital.utils.Paginacao;
import br.edu.ifpb.gestaobibliotecadigital.views.components.UpdateObserver;
import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;

public class PesquisaAvancadaLivros extends javax.swing.JPanel {

    public final UpdateObserver events = new UpdateObserver();
    private LivroFiltro filtro = new LivroFiltro();
    private LivroService livroService = new LivroService();

    public PesquisaAvancadaLivros() {
        initComponents();
        initEnterPress();
        categoriaComboBox.setModel(new DefaultComboBoxModel<>(Helpers.CATEGORIAS));
        anoPublicacaoComboBox.setModel(new DefaultComboBoxModel<>(Helpers.getAnos()));
    }

    /**
     * Retorna o filtro atual
     *
     * @return
     */
    public LivroFiltro getFiltro() {
        return filtro;
    }

    /**
     * Configura para quando pressionar enter em qualquer TextField, executar a
     * pesquisa
     */
    private void initEnterPress() {
        ActionListener enter = evt -> {
            pesquisarActionPerformed(evt);
        };

        for (Component component : getComponents()) {
            if (component instanceof JTextField jTextField) {
                jTextField.addActionListener(enter);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        nomeAutorLabel = new javax.swing.JLabel();
        nomeAutor = new javax.swing.JTextField();
        nomeEditoraLabel = new javax.swing.JLabel();
        nomeEditora = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        nomeCategoriaLabel = new javax.swing.JLabel();
        categoriaComboBox = new javax.swing.JComboBox<>();
        anoPublicacaoLabel = new javax.swing.JLabel();
        anoPublicacaoComboBox = new javax.swing.JComboBox<>();

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titulo.setText("Pesquisa Avançada");

        nomeAutorLabel.setText("Nome do Autor");

        nomeEditoraLabel.setText("Nome da Editora");

        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        nomeCategoriaLabel.setText("Categoria");

        anoPublicacaoLabel.setText("Ano de publicação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeAutor)
                    .addComponent(nomeEditora)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeCategoriaLabel)
                            .addComponent(titulo)
                            .addComponent(nomeAutorLabel)
                            .addComponent(nomeEditoraLabel))
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anoPublicacaoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(anoPublicacaoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoriaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeAutorLabel)
                .addGap(5, 5, 5)
                .addComponent(nomeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeEditoraLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeCategoriaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoriaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anoPublicacaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anoPublicacaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Limpa a pesquisa
     */
    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        nomeAutor.setText("");
        nomeEditora.setText("");
        categoriaComboBox.setSelectedIndex(0);
        anoPublicacaoComboBox.setSelectedIndex(0);
        this.filtro = new LivroFiltro();

       
        events.emit();
    }//GEN-LAST:event_limparActionPerformed

    /**
     * Executa a pesquisa
     */
    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        LivroFiltro filtroParaPesquisar = new LivroFiltro();

        String nomeAutorText = nomeAutor.getText().trim();
        String nomeEditoraText = nomeEditora.getText().trim();
        String categoriaSelecionada = categoriaComboBox.getSelectedItem().toString();
        String categoria = (categoriaSelecionada.equalsIgnoreCase("Selecione...")) ? "" : categoriaSelecionada;

        String anoSelecionado = anoPublicacaoComboBox.getSelectedItem().toString();
        int anoPublicaoLivro = (anoSelecionado.equalsIgnoreCase("Selecione um ano")) ? 0 : Integer.parseInt(anoSelecionado);

        if (!nomeAutorText.equals("")) {
            filtroParaPesquisar.porPalavra(nomeAutorText);
        }
        
        if (!categoria.equals("")) {
            livroService.registrarBuscaPorCategoria(categoria);
            filtroParaPesquisar.porCategoria(categoria);
        }

        if (anoPublicaoLivro != 0) {
            filtroParaPesquisar.porAno(anoPublicaoLivro);
        }

        // Filtro por ano
        this.filtro = filtroParaPesquisar;
        events.emit();
    }//GEN-LAST:event_pesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> anoPublicacaoComboBox;
    private javax.swing.JLabel anoPublicacaoLabel;
    private javax.swing.JComboBox<String> categoriaComboBox;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField nomeAutor;
    private javax.swing.JLabel nomeAutorLabel;
    private javax.swing.JLabel nomeCategoriaLabel;
    private javax.swing.JTextField nomeEditora;
    private javax.swing.JLabel nomeEditoraLabel;
    private javax.swing.JButton pesquisar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
